import { timingSafeEqual } from "node:crypto";
import { eq } from "drizzle-orm";
import { db } from "../db/client.js";
import { sites, users } from "../db/schema.js";
import { hashToken } from "./tokens.js";

interface AppReviewConfig {
  email: string;
  accessCodeHash: string;
  siteSubdomain: string;
  siteTitle: string;
}

const RESERVED_SUBDOMAINS = new Set(["api", "www", "app", "admin", "mail", "ftp"]);

function config(): AppReviewConfig | null {
  if (process.env.APP_REVIEW_ACCESS_CODE?.trim()) {
    throw new Error(
      "APP_REVIEW_ACCESS_CODE is not accepted because it stores a long-lived credential in plaintext. " +
        "Use APP_REVIEW_ACCESS_CODE_HASH generated by npm run app-review:credential.",
    );
  }

  const email = process.env.APP_REVIEW_EMAIL?.trim().toLowerCase();
  const accessCodeHash = process.env.APP_REVIEW_ACCESS_CODE_HASH?.trim().toLowerCase();
  const siteSubdomain = process.env.APP_REVIEW_SITE_SUBDOMAIN?.trim().toLowerCase();
  const siteTitle = process.env.APP_REVIEW_SITE_TITLE?.trim();
  const values = [email, accessCodeHash, siteSubdomain, siteTitle];

  if (values.every((value) => !value)) return null;
  if (values.some((value) => !value)) {
    throw new Error(
      "App Review access requires APP_REVIEW_EMAIL, APP_REVIEW_ACCESS_CODE_HASH, " +
        "APP_REVIEW_SITE_SUBDOMAIN, and APP_REVIEW_SITE_TITLE together.",
    );
  }
  if (!email!.includes("@")) throw new Error("APP_REVIEW_EMAIL must be an email address.");
  if (!/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])$/.test(siteSubdomain!)) {
    throw new Error(
      "APP_REVIEW_SITE_SUBDOMAIN must be 2-63 lowercase letters, numbers, or interior hyphens.",
    );
  }
  if (RESERVED_SUBDOMAINS.has(siteSubdomain!)) {
    throw new Error("APP_REVIEW_SITE_SUBDOMAIN is reserved.");
  }
  if (!/^[a-f0-9]{64}$/.test(accessCodeHash!)) {
    throw new Error(
      "APP_REVIEW_ACCESS_CODE_HASH must be a lowercase SHA-256 hex digest generated by npm run app-review:credential.",
    );
  }
  if (siteTitle!.length > 200) throw new Error("APP_REVIEW_SITE_TITLE must be at most 200 characters.");

  return { email: email!, accessCodeHash: accessCodeHash!, siteSubdomain: siteSubdomain!, siteTitle: siteTitle! };
}

export function validateAppReviewConfiguration(): void {
  config();
}

function codesMatch(provided: string, expectedHash: string): boolean {
  const providedHash = Buffer.from(hashToken(provided), "hex");
  const configuredHash = Buffer.from(expectedHash, "hex");
  return providedHash.length === configuredHash.length && timingSafeEqual(providedHash, configuredHash);
}

/**
 * Optional, test-server-only App Review access. Unlike ordinary owner claims,
 * this credential is deliberately reusable so Apple's review can happen at an
 * unknown time and on more than one device. It is enabled only when all four
 * APP_REVIEW_* environment values are configured.
 */
export async function claimAppReviewAccount(code: string) {
  const review = config();
  if (!review || !codesMatch(code, review.accessCodeHash)) return null;

  let [user] = await db.select().from(users).where(eq(users.email, review.email)).limit(1);
  if (!user) {
    [user] = await db.insert(users).values({ email: review.email }).returning();
  }

  const [ownedSite] = await db.select().from(sites).where(eq(sites.ownerUserId, user.id)).limit(1);
  if (ownedSite && ownedSite.subdomain !== review.siteSubdomain) {
    throw new Error(
      `APP_REVIEW_EMAIL already owns site "${ownedSite.subdomain}"; use a dedicated review email address.`,
    );
  }
  if (!ownedSite) {
    const [subdomainOwner] = await db.select().from(sites).where(eq(sites.subdomain, review.siteSubdomain)).limit(1);
    if (subdomainOwner) {
      throw new Error(`APP_REVIEW_SITE_SUBDOMAIN "${review.siteSubdomain}" is already in use.`);
    }
    await db.insert(sites).values({
      ownerUserId: user.id,
      subdomain: review.siteSubdomain,
      title: review.siteTitle,
      profileName: review.siteTitle,
      // A reviewer should never accidentally federate test posts from a
      // disposable server. They can still exercise every local publishing
      // and public-rendering path.
      federationEnabled: false,
    });
  }

  return user;
}
